name: Build Mudlet Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Check folder exists
      run: |
        ls
        test -d "Achaean System" && echo "✅ Folder found" || echo "❌ Folder missing"

    - name: Create .mpackage zip
      run: |
        set -e
        zip -r "Achaean System.mpackage" "Achaean System"
        ls -lh

    - name: Upload .mpackage as artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Achaean System
        path: Achaean System.mpackage
