name: Build Mudlet Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify folder exists
      run: ls -la

    - name: Create .mpackage zip
      run: zip -r "Achaean System.mpackage" "Achaean System"

    - name: Upload .mpackage as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Achaean System
        path: Achaean System.mpackage
